
title: Mureca Multirepuestos Cavero
url: https://murecamultirepuestoscavero.netlify.app/
description:  En Mureca Multirepuesto Cavero Cochabamba-Bolivia usted puede encontrar numerosos artículos de accesorios desde chasis, carroceria, motor y electrico de coches Japonese Y Americanos 

social:
  name: Mureca Multirepuestos Cavero
  links:
    - https://www.facebook.com/importadoramureca
    
language: "es"

tag_page_layout: 
tag_page_dir: 

collections:
  product_tags:
      output: true
  productos:
    output: true
    permalink: /repuestos/:path/
  
defaults:
  - scope:
      path: ""
      type: "productos"
    values:
      layout: "productos"


google_analytics: G-MRLSNC5CNS

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll/tagging

exclude:
  - Gemfile
  - Gemfile.lock


algolia:
  #settings: false
  application_id: JIP7JIGUL5
  index_name: mureca
  search_only_api_key: 1665ebdd3ae5ee916f46e34186df9769
  
  files_to_exclude:
    - index.html
    - index.md
    - contacto.md
    - nosotros.md
    - preguntas-frecuentes.md
    - product-details.html
    - producto.md
    - servicios.md
    - shop.html
    - politicas-de-privacidad.html
    - multirepuestos-cavero-suzuki-parachoques.html
    - mureca-multirepuestos-cavero-suzuki-mascara.html
    - 404.html
    - mostrar.html
    - prueba.html
    - mureca-productos-filtro.html
  
exclude:
  - Gemfile
  - Gemfile.lock
  